import type { Metadata } from "next";
import { Geist_Mono, Manrope } from "next/font/google";
import "@/styles/global.css";
import AppHeader from "@/components/layout/header";
import AppFooter from "@/components/layout/footer";
import { ThemeProvider } from "next-themes";

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const manrope = Manrope({
  subsets: ["latin", "vietnamese"],
  weight: ["300", "400", "500", "600", "700", "800"],
  variable: "--font-manrope",
});

export const metadata: Metadata = {
  title: "Rental Listing Platform",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="vi" className="light">
      <body className={`${manrope.variable} ${geistMono.variable} antialiased`}>
        <AppHeader />
        {children}
        <AppFooter />
      </body>
    </html>
  );
}
